### ISSUE TITLE
Freezes during Code Block creation

### ISSUE THREAD

**Issue by wipeoutmedia** [wipeoutmedia/css-javascript-toolbox#1]
On 17 Feb 2016, at 12:26 am, Byron Solomon <byron@byronsolomon.com> wrote:

When I try to create a new code block with CSS & Javascript Toolbox PLUS on my site running Divi 2.6.2, it freezes during creation and I have to stop it by clicking the "X" to close the popup. Is there a fix for this?

******************************
Byron Solomon
ByronSolomon.com
All Ohs

Error generated:
Uncaught TypeError: Cannot read property 'CJTBlock' of undefinedCJTBlocksPage.addBlock @ blocks-page.js:414(anonymous function) @ add-new-block.js:80m.isFunction.e @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate&ver=4.4.2:2j @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,quicktags,sack&ver=4.4.2:2k.fireWith @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,quicktags,sack&ver=4.4.2:2x @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,quicktags,sack&ver=4.4.2:5b @ load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,quicktags,sack&ver=4.4.2:5

____________________________________

On Wed, Feb 17, 2016 at 9:22 AM, CSS JS Toolbox Support <support@css-javascript-toolbox.com> wrote:
Hi Byron,

Sorry for the inconvenience you are currently experiencing.
Can you please send me temporary admin login details so I can see what is going on there.

Kind Regards,
Damian Baker

CSS JS TOOLBOX
e:  info@css-javascript-toolbox.com
w:  http://css-javascript-toolbox.com

____________________________________

Damian,

Thanks for getting back to me. The temp login info is below:

site: http://www.privatelendingmadeeasy.com/wp-admin/
username: --------------
pw: -------------------

******************************
Byron Solomon
ByronSolomon.com
All Ohs

**Comment by ivanwebpro** [comment]
I discovered that this problems occurs due to poor code in the plugin "1shoppingcartcom-wordpress-signup-forms", WordPress Signup Forms, https://wordpress.org/plugins/1shoppingcartcom-wordpress-signup-forms/, not updated for 6 years :)

Issue with plugin "1shoppingcartcom-wordpress-signup-forms" is solved, first block was successfully created.

But this block is not displayed in dashboard at all. I am exploring this issue.

Second problem was related to support post tags in Plus version (but fixes was made in free version).

Now both problem was solved by commits:

wipeoutmedia/css-javascript-toolbox@41a9621
wipeoutmedia/css-javascript-toolbox@19a110a
wipeoutmedia/css-javascript-toolbox@236a99e
wipeoutmedia/css-javascript-toolbox@9fc03c2

Also I changed files in his hosting, so now CJT working correctly.

And removed login details from the post above.
